In [39]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report, plot_confusion_matrix, confusion_matrix,accuracy_score
from sklearn import metrics

In [40]:
df = pd.read_csv('combined-dataset.csv')
print (df.columns)
df.head(20)

Index(['gold', 'platinum', 'palladium', 'tungsten', 'silver', 'y'], dtype='object')


gold  platinum  palladium  tungsten  silver  y
0   43520     22464      21397     20007   24313  1
1   43534     22031      21513     19904   24052  1
2   43534     22554      21243     20086   24285  1
3   43588     22347      21179     20285   24279  1
4      75     22583      21516     19634   24203  1
5   23144     21949      20841     20448   24490  1
6   27635     22280      21984     19521   24288  1
7   26400     22167      20833     20764   24113  1
8   27318     23069      21733     19636   24339  1
9   26469     21838      20803     20391   24088  1
10  27592     22882      21836     19825   24786  1
11  27320     21556      21462     20356   23681  1
12  27972     23305      21345     20418   24669  1
13  27157     21967      21440     19972   23714  1
14  27672     22802      21156     20011   24526  1
15  26952     22019      21381     19878   24304  1
16  27800     22400      21357     19830   24297  1
17  27434     22360      21101     20638   24166  1
18  28458     22514      21637     19685   24032  1
19  27093     22005      20652     20327   24523  1

In [41]:

X = df.iloc[:,:5].values
Y = df.iloc[:,5:6].values

ohe = OneHotEncoder()
Y = ohe.fit_transform(Y).toarray()
print('One hot encoded array:')
print(Y[:5])

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.4,random_state = 42)
print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))


One hot encoded array:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(140220, 5)
(140220, 13)
[0. 1.]


In [42]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [44]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion matrix",classification_report(y_test, y_pred))

Accuracy: 0.6228391099700471
Confusion matrix               precision    recall  f1-score   support

           0       0.64      0.63      0.64     15492
           1       0.35      0.36      0.36      7289
           2       0.80      0.80      0.80      7352
           3       0.36      0.37      0.37      4866
           4       0.44      0.45      0.45      7354
           5       0.53      0.53      0.53      4960
           6       0.97      0.98      0.98      7329
           7       0.38      0.38      0.38      7322
           8       0.46      0.45      0.45      7508
           9       0.81      0.82      0.82      6641
          10       0.97      0.97      0.97      4987
          11       0.76      0.74      0.75      7419
          12       0.63      0.62      0.62      4961

   micro avg       0.62      0.62      0.62     93480
   macro avg       0.62      0.62      0.62     93480
weighted avg       0.62      0.62      0.62     93480
 samples avg       0.62      0.62 