In [18]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [19]:
dataset = pd.read_csv('combined-dataset.csv')
print(dataset.columns)
dataset.head(20)

Index(['gold', 'platinum', 'palladium', 'tungsten', 'silver', 'y'], dtype='object')


gold  platinum  palladium  tungsten  silver  y
0   43520     22464      21397     20007   24313  1
1   43534     22031      21513     19904   24052  1
2   43534     22554      21243     20086   24285  1
3   43588     22347      21179     20285   24279  1
4      75     22583      21516     19634   24203  1
5   23144     21949      20841     20448   24490  1
6   27635     22280      21984     19521   24288  1
7   26400     22167      20833     20764   24113  1
8   27318     23069      21733     19636   24339  1
9   26469     21838      20803     20391   24088  1
10  27592     22882      21836     19825   24786  1
11  27320     21556      21462     20356   23681  1
12  27972     23305      21345     20418   24669  1
13  27157     21967      21440     19972   23714  1
14  27672     22802      21156     20011   24526  1
15  26952     22019      21381     19878   24304  1
16  27800     22400      21357     19830   24297  1
17  27434     22360      21101     20638   24166  1
18  28458     22514      21637     19685   24032  1
19  27093     22005      20652     20327   24523  1

In [20]:
X = dataset.iloc[:,:5].values
y = dataset.iloc[:,5:6].values

ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()
print('One hot encoded array:')
print(y[:5])

scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.4,random_state = 42)
print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))

One hot encoded array:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(140220, 5)
(140220, 13)
[0. 1.]


In [ ]:

model = keras.Sequential()
model.add(keras.layers.Dense(5, input_shape=(5,)))
#model.add(keras.layers.Dense(120, activation='relu'))

model.add(keras.layers.Dense(190, activation='relu'))
model.add(keras.layers.Dense(300, activation='relu'))

model.add(keras.layers.Dense(13, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=300)
model.summary()

Epoch 1/300
4382/4382 [==============================] - 11s 2ms/step - loss: 1.6009 - accuracy: 0.4232
Epoch 2/300
4382/4382 [==============================] - 10s 2ms/step - loss: 1.3171 - accuracy: 0.5176
Epoch 3/300
4382/4382 [==============================] - 12s 3ms/step - loss: 1.2273 - accuracy: 0.5448
Epoch 4/300
4382/4382 [==============================] - 12s 3ms/step - loss: 1.1762 - accuracy: 0.5609
Epoch 5/300
4382/4382 [==============================] - 12s 3ms/step - loss: 1.1446 - accuracy: 0.5713
Epoch 6/300
4382/4382 [==============================] - 9s 2ms/step - loss: 1.1241 - accuracy: 0.5793
Epoch 7/300
4382/4382 [==============================] - 9s 2ms/step - loss: 1.1087 - accuracy: 0.5858
Epoch 8/300
4382/4382 [==============================] - 9s 2ms/step - loss: 1.0948 - accuracy: 0.5890
Epoch 9/300
4382/4382 [==============================] - 12s 3ms/step - loss: 1.0830 - accuracy: 0.5934 0s - loss: 1
Epoch 10/300
4382/4382 [==============================

4382/4382 [==============================] - 9s 2ms/step - loss: 0.8414 - accuracy: 0.6907
Epoch 80/300
4382/4382 [==============================] - 8s 2ms/step - loss: 0.8400 - accuracy: 0.6902
Epoch 81/300
4382/4382 [==============================] - 8s 2ms/step - loss: 0.8413 - accuracy: 0.6905
Epoch 82/300
4382/4382 [==============================] - 9s 2ms/step - loss: 0.8387 - accuracy: 0.6916
Epoch 83/300
4382/4382 [==============================] - 8s 2ms/step - loss: 0.8400 - accuracy: 0.6905
Epoch 84/300
4382/4382 [==============================] - 8s 2ms/step - loss: 0.8381 - accuracy: 0.6913
Epoch 85/300
4382/4382 [==============================] - 7s 2ms/step - loss: 0.8394 - accuracy: 0.6911
Epoch 86/300
4382/4382 [==============================] - 8s 2ms/step - loss: 0.8366 - accuracy: 0.6917
Epoch 87/300
4382/4382 [==============================] - 9s 2ms/step - loss: 0.8359 - accuracy: 0.6931
Epoch 88/300
4382/4382 [==============================] - 9s 2ms/step - loss:

In [ ]:
predications = model.predict(X_test)
y_pred = list()
for i in range(len(predications)):
    y_pred.append(np.argmax(predications[i]))

ytest = list()
for i in range(len(y_test)):
    ytest.append(np.argmax(y_test[i]))

print('Accuracy is:', accuracy_score(ytest, y_pred)*100)
print('confusion_matrix ',confusion_matrix(ytest,y_pred))
print("Confusion matrix",classification_report(y_test, y_pred))
